--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KRUNCHSHooT/LibTrimArmor
build-by-default: true
branches:
- master
projects:
  LibTrimArmor:
    path: ""
    model: virion
    type: library
...
